### ISSUE TITLE
Unencrypted md5 incorrect

### ISSUE THREAD

**Issue by h5t4** [elixir-europe/human-data-local-ega#2]
I tried to set up it and ended with following error message (point 11 in documentation):

Unencrypted md5 incorrect: d41d8cd98f00b204e9800998ecf8427e vs 95db6497dbefa0a009ad6ced6ba56cda at /EGA_local/public/process_file.pl line 270.

 This md5sum represents empty line. For example :
ega@ubuntu-ega:~/EGA_local$ echo -n "" | md5sum
d41d8cd98f00b204e9800998ecf8427e  -

I also added sleep inside if statement to manually check url with curl (installed curl also) before container removal and return value  was indeed empty thing.

**Comment by jdylan** [comment]
Hi,
Can you list the contents of /home/ega/EGA_local/public/submission/ftpusers/bob/
plus the contents of /home/ega/EGA_local/public/submission/ftpusers/bob/ALL.chr22.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.vcf.gz.md5 please?
Thanks

**Comment by h5t4** [comment]
ega@ega:~$ ls /home/ega/EGA_local/public/submission/ftpusers/bob/ && cat /home/ega/EGA_local/public/submission/ftpusers//bob/ALL.chr22.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.vcf.gz.md5
ALL.chr22.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.vcf.gz.gpg
ALL.chr22.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.vcf.gz.gpg.md5
ALL.chr22.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.vcf.gz.md5
95db6497dbefa0a009ad6ced6ba56cda  ALL.chr22.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.vcf.gz

**Comment by jdylan** [comment]
OK, the call to the re-encryption service is failing - and as you have shown the re-encryption service is getting the md6 of an empty line (or file). This suggests the file does not exist in the archive location - can you check if there is a file in the archive location (default would be /home/ega/EGA_local/private/archive) please?

**Comment by h5t4** [comment]
Thank You. The hint was helpful. Mentioned directory contains only one file 'test.gpg'. This Issue resolved. 

api container was dead:
ega@ega:~/EGA_local$ docker logs api
/etc/monitrc:32: Program does not exist: '/EGA_local/scripts/public/datad.sh'

My action was:
mkdir /home/ega/EGA_local/scripts && ln -s /home/ega/EGA_local/public/scripts /home/ega/EGA_local/scripts/public
docker rm archive
docker rm api

After that I recreated containers as documented.
